# Habilita Virtual Threads (Java 21)
spring.threads.virtual.enabled=true

# Configuracao de Datasource (PostgreSQL)
spring.datasource.url=jdbc:postgresql://localhost:5433/core_banking
spring.datasource.username=postgres
spring.datasource.password=CCpp1153
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update


# Exibir SQL no console (ajuda no debug)
spring.jpa.show-sql=true

# OpenAPI/Swagger
springdoc.api-docs.path=/api-docs

